
population:
  mean_stochastic_interactions: 22
  probability_to_remember_random_meeting: 0.8

virus:
  transmission_probability: 0.0165
  transmission_probability_household: 0.0
  infectious_days_mean: 6.5
  infectious_days_std: 1


# mean time after which a person who contracted the virus
# starts being infectious
infectious_start_mean: 5
infectious_start_std: 1

# mean time after which a person who contracted the virus
# starts needing hospitalization
hospitalization_start_mean: 10
hospitalization_start_std: 1.5

hospitalization_length_mean: 8
hospitalization_length_std: 1

critical_care_start_mean: 6
critical_care_start_std: 1.5

critical_care_length_mean: 10
critical_care_length_std: 1

migration_matrix_txt: data/sensitive/migrations.txt
populations_file_txt: data/municipalities.txt

result_file: results/results_busines_as_usual.json

# numerical number of inital number of infected at the simulation start (will be selected randomly in this case). If not defined, the text file with number of infected will be used.
initial_number_of_infected: 100

# test file with number of infected people in municipalities
#infected_distribution_file: data/infected.txt

# age distribution of people in country
age_distribution_file: data/age_distribution.json

# tracking of contants (disabled, infected-only, all)
tracking: infected_only

age_symptoms_file: data/age_symptoms.json

